name: Update Script Catalog

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update catalog
        run: |
          mkdir -p tools
          node --version
          node tools/update_catalog.mjs || { echo "Generator failed"; exit 1; }

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes" || git commit -m "chore: auto-update Script Catalog"
          git push
